let data = [
  {
    TBNmediaId: "",
    mediaid: "",
    title: "",
    programName: "",
    seasonNumber: "",
    episodeNumber: "",
    hqme: "",
    publish_start_date: "",
    publish_end_date: "",
    rating: "",
    releaseDate: "",
    requiresSubscription: "",
    revShare: "",
    hosting_type: "",
    status: "",
    "": "",
    tags: "",
    __1: "",
    seriesID: "",
    mediaId: "",
    showcaseURL: "",
    showcaseURL__1: "",
    "OLD URL": "",
    __2: "",
  },
  {
    TBNmediaId: "HD-OTTMV0353",
    mediaid: "JUMfoH8K",
    title: "Freetown",
    programName: "Freetown",
    seasonNumber: 1,
    episodeNumber: 353,
    hqme: "",
    publish_start_date: "2022-03-02T21:40:00+00:00",
    publish_end_date: "2222-03-28T20:40:00+00:00",
    rating: "TV-G",
    releaseDate: "2015-04-08T20:40:00Z",
    requiresSubscription: "",
    revShare: "",
    hosting_type: "hosted",
    status: "ready",
    "": "",
    tags: "['Faith', 'Fear', 'Missionary', 'War', 'Movie', 'Drama', 'seriesId_', 'Courage', 'Near Death', 'Freetown', 'Garrett Batty', 'Henry Adofo', 'Michael Attram', 'Alphonse Menyo', 'Phillip Adekunle Michael']",
    __1: "https://watch.tbn.org/m/JUMfoH8K",
    seriesID: "/m",
    mediaId: "/JUMfoH8K",
    showcaseURL: "/m/JUMfoH8K",
    showcaseURL__1: "https://watch.tbn.org/m/JUMfoH8K",
    "OLD URL": "not found",
    __2: "",
  },
  {
    TBNmediaId: "HD-P012522R",
    mediaid: "eSiXYHSW",
    title: "Praise - Joyce Meyer - January 25, 2022",
    programName: "Praise",
    seasonNumber: 50,
    episodeNumber: 10,
    hqme: 1,
    publish_start_date: "2022-01-26T01:00:00+00:00",
    publish_end_date: "2222-01-26T02:00:00+00:00",
    rating: "TV-G",
    releaseDate: "2022-01-24T17:13:00Z",
    requiresSubscription: "",
    revShare: "",
    hosting_type: "hosted",
    status: "ready",
    "": "",
    tags: "['Laurie Crouch', 'Testimony', 'Faith', 'Author', 'Trust God', 'Prayer', 'Praise', 'Religion', 'Trials-Hard Times', 'Attitude', 'Thinking', 'Thankfulness', 'Matt Crouch', 'Episode', 'Talk Show', 'seriesId_', 'Sexual Abuse', 'Joyce Meyer', 'Gratitude', 'Loss', 'Death', 'Natural Disaster', 'Philippians 4:13', 'Romans 12:21', '2 Corinthians 12:8-9', 'Philippians 2:14-15']",
    __1: "https://watch.tbn.org/m/eSiXYHSW",
    seriesID: "/m",
    mediaId: "/eSiXYHSW",
    showcaseURL: "/m/eSiXYHSW",
    showcaseURL__1: "https://watch.tbn.org/m/eSiXYHSW",
    "OLD URL": "https://watch.tbn.org/videos/hd-p012522r",
    __2: "",
  },
  {
    TBNmediaId: "HD-OTTMV0356",
    mediaid: "fO24UwlT",
    title: "In The Name Of God",
    programName: "In The Name Of God",
    seasonNumber: 1,
    episodeNumber: 356,
    hqme: "",
    publish_start_date: "2022-03-04T02:05:00+00:00",
    publish_end_date: "2122-03-29T01:05:00+00:00",
    rating: "TV-G",
    releaseDate: "2013-11-02T01:05:00Z",
    requiresSubscription: "",
    revShare: "",
    hosting_type: "hosted",
    status: "ready",
    "": "",
    tags: "['Hope', 'Trust God', 'Honor', 'Lord', 'Christ', 'Jesus', 'Truth', 'Respect', 'Movie', 'Drama', 'seriesId_', 'Holiness', 'Giving', 'Divination', 'In The Name Of God', 'Kevan Otto', 'John Ratzenberger', 'Eric Roberts', 'Patrick Davis Alarcón', 'Pete Freeland']",
    __1: "https://watch.tbn.org/m/fO24UwlT",
    seriesID: "/m",
    mediaId: "/fO24UwlT",
    showcaseURL: "/m/fO24UwlT",
    showcaseURL__1: "https://watch.tbn.org/m/fO24UwlT",
    "OLD URL": "not found",
    __2: "",
  },
];
